### ISSUE TITLE
Crash in settings activity

### ISSUE THREAD

**Issue by bravelocation** [bravelocation/yeltzland-android#27]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bravelocation.yeltzland/com.bravelocation.yeltzland.SettingsActivity}: java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout
       at com.bravelocation.yeltzland.SettingsActivity.onPostCreate(SettingsActivity.java:34)
       at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1207)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by bravelocation** [comment]
Fixed in 2.1.3 - not sure what crap was in the activity, but moved back to sensible code now
